{{- if index .Values "jenkins-x-platform" "jenkins" "enabled" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: jenkins
spec:
  rules:
  - host: jenkins{{ index .Values "jxboot-resources" "cluster" "namespaceSubDomain" }}{{ index .Values "jxboot-resources" "cluster" "domain"  }}
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
{{- if index .Values "jxboot-resources" "cluster" "tls" }}
  tls:
  - hosts:
    - jenkins{{ index .Values "jxboot-resources" "cluster" "namespaceSubDomain" }}{{ index .Values "jxboot-resources" "cluster" "domain"  }}
{{- if eq (index .Values "jxboot-resources" "certmanager" "production") "true" }}
    secretName: "tls-{{ index .Values "jxboot-resources" "cluster" "domain" | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ index .Values "jxboot-resources" "cluster" "domain" | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
